name: Rancher Host-subnet Networking
description: |
  Rancher Networking plugin using host-subnet.
version: v0.0.1
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
