name: Rancher L3-Routing Networking
description: |
  Rancher Networking plugin using l3 routing.
version: v0.0.1
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
