.catalog:
  name: "aws-vpc"
  version: "v0.0.1"    # Keep this in sync with calico/node tag version
  questions:
    - variable: "LOG_LEVEL"
      label: "Enable Debug Logs"
      description: "This will enable very verbose debug logs."
      type: "enum"
      default: "DEBUG"
      required: true
      options:
        - "DEBUG"
        - "INFO"
    - variable: MTU
      label: "MTU for the network"
      description: "Adjust the MTU for the network"
      required: true
      default: 1500
      type: int

aws-vpc:
  network_driver:
    name: Rancher AWS VPC
    default_network:
      name: aws-vpc
      host_ports: true
      dns:
      - 169.254.169.250
      dns_search:
      - rancher.internal
    cni_config:
      '10-aws-vpc.conf':
        name: aws-vpc-network
        type: rancher-bridge
        bridge: docker0
        log_level: ${LOG_LEVEL}
        isDefaultGateway: true
        hostNat: true
        hairpinMode: true
        isAWSVPC: true
        mtu: ${MTU}
        ipam:
          type: rancher-host-local-ipam
          routes:
          - dst: 169.254.169.250/32
